# Generated by Django 4.1.2 on 2022-10-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BuoyMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buoys.measurement')),
                ('altitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            bases=('buoys.measurement',),
        ),
        migrations.CreateModel(
            name='EchoLocationMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buoys.measurement')),
                ('data', models.IntegerField()),
            ],
            bases=('buoys.measurement',),
        ),
        migrations.CreateModel(
            name='LightMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buoys.measurement')),
                ('light_level', models.FloatField()),
            ],
            bases=('buoys.measurement',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_type', models.CharField(max_length=40)),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buoys.buoy')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buoys.sensor'),
        ),
    ]
