# Generated by Django 4.1.2 on 2022-10-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_type', models.CharField(max_length=40)),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='buoys.buoy')),
            ],
        ),
        migrations.CreateModel(
            name='LightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('light_level', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_measurements', to='buoys.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='EchoLocationMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('data', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echo_measurements', to='buoys.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='BuoyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('altitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buoy_measurements', to='buoys.sensor')),
            ],
        ),
    ]
