# Generated by Django 4.1.2 on 2022-10-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buoys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='buoy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='buoys.buoy'),
        ),
    ]
