# Generated by Django 4.1.2 on 2022-10-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BouyMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bouys.measurement')),
                ('altitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            bases=('bouys.measurement',),
        ),
        migrations.CreateModel(
            name='EchoLocationMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bouys.measurement')),
                ('data', models.IntegerField()),
            ],
            bases=('bouys.measurement',),
        ),
        migrations.CreateModel(
            name='LightMeasurement',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bouys.measurement')),
                ('light_level', models.FloatField()),
            ],
            bases=('bouys.measurement',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_type', models.IntegerField()),
                ('bouy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouys.bouy')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouys.sensor'),
        ),
    ]
