# Generated by Django 4.1.2 on 2022-10-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='s_id',
            new_name='sensor',
        ),
    ]
